// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DBSize(arg1) {
  return window['go']['main']['App']['DBSize'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteKey(arg1, arg2) {
  return window['go']['main']['App']['DeleteKey'](arg1, arg2);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function GetKeyInfo(arg1, arg2) {
  return window['go']['main']['App']['GetKeyInfo'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetValue(arg1, arg2) {
  return window['go']['main']['App']['GetValue'](arg1, arg2);
}

export function HDel(arg1, arg2, arg3) {
  return window['go']['main']['App']['HDel'](arg1, arg2, arg3);
}

export function HSet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['HSet'](arg1, arg2, arg3, arg4);
}

export function IsConnected(arg1) {
  return window['go']['main']['App']['IsConnected'](arg1);
}

export function LPush(arg1, arg2, arg3) {
  return window['go']['main']['App']['LPush'](arg1, arg2, arg3);
}

export function LRem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LRem'](arg1, arg2, arg3, arg4);
}

export function LSet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LSet'](arg1, arg2, arg3, arg4);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function RPush(arg1, arg2, arg3) {
  return window['go']['main']['App']['RPush'](arg1, arg2, arg3);
}

export function RenameKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameKey'](arg1, arg2, arg3);
}

export function SAdd(arg1, arg2, arg3) {
  return window['go']['main']['App']['SAdd'](arg1, arg2, arg3);
}

export function SRem(arg1, arg2, arg3) {
  return window['go']['main']['App']['SRem'](arg1, arg2, arg3);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['ScanKeys'](arg1, arg2, arg3);
}

export function SearchValue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchValue'](arg1, arg2, arg3, arg4);
}

export function SelectDB(arg1, arg2) {
  return window['go']['main']['App']['SelectDB'](arg1, arg2);
}

export function SetString(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetString'](arg1, arg2, arg3, arg4);
}

export function SetTTL(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTTL'](arg1, arg2, arg3);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function ZAdd(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ZAdd'](arg1, arg2, arg3, arg4);
}

export function ZRem(arg1, arg2, arg3) {
  return window['go']['main']['App']['ZRem'](arg1, arg2, arg3);
}
