// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function Connect(arg1:string):Promise<main.ConnectResult>;

export function DBSize(arg1:string):Promise<number>;

export function DeleteConnection(arg1:string):Promise<config.OperationResult>;

export function DeleteKey(arg1:string,arg2:string):Promise<config.OperationResult>;

export function Disconnect(arg1:string):Promise<config.OperationResult>;

export function GetKeyInfo(arg1:string,arg2:string):Promise<config.RedisKey>;

export function GetSettings():Promise<config.AppSettings>;

export function GetValue(arg1:string,arg2:string,arg3:number,arg4:number):Promise<config.KeyValue>;

export function HDel(arg1:string,arg2:string,arg3:string):Promise<config.OperationResult>;

export function HSet(arg1:string,arg2:string,arg3:string,arg4:string):Promise<config.OperationResult>;

export function IsConnected(arg1:string):Promise<boolean>;

export function LPush(arg1:string,arg2:string,arg3:string):Promise<config.OperationResult>;

export function LRem(arg1:string,arg2:string,arg3:number,arg4:string):Promise<config.OperationResult>;

export function LSet(arg1:string,arg2:string,arg3:number,arg4:string):Promise<config.OperationResult>;

export function ListConnections():Promise<Array<config.ConnectionConfig>>;

export function RPush(arg1:string,arg2:string,arg3:string):Promise<config.OperationResult>;

export function RenameKey(arg1:string,arg2:string,arg3:string):Promise<config.OperationResult>;

export function SAdd(arg1:string,arg2:string,arg3:string):Promise<config.OperationResult>;

export function SRem(arg1:string,arg2:string,arg3:string):Promise<config.OperationResult>;

export function SaveConnection(arg1:config.ConnectionConfig):Promise<config.OperationResult>;

export function SaveSettings(arg1:config.AppSettings):Promise<config.OperationResult>;

export function ScanKeys(arg1:string,arg2:string,arg3:number,arg4:number):Promise<config.ScanResult>;

export function SearchValue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<config.KeyValue>;

export function SelectDB(arg1:string,arg2:number):Promise<config.OperationResult>;

export function SetString(arg1:string,arg2:string,arg3:string,arg4:number):Promise<config.OperationResult>;

export function SetTTL(arg1:string,arg2:string,arg3:number):Promise<config.OperationResult>;

export function TestConnection(arg1:config.ConnectionConfig):Promise<config.OperationResult>;

export function ZAdd(arg1:string,arg2:string,arg3:string,arg4:number):Promise<config.OperationResult>;

export function ZRem(arg1:string,arg2:string,arg3:string):Promise<config.OperationResult>;
